// Mock data para portfolio — Dashboard e Gerenciar
import type { Apontamento } from './ApontamentosContext'

export const MOCK_APONTAMENTOS: Apontamento[] = [
  {
    "id": "demo-cl-0001__nc-01",
    "checklistId": "demo-cl-0001",
    "ncItemId": "nc-01",
    "veiculoId": "veiculo_CTD00M2",
    "placa": "CTD00M2",
    "modelo": "HILUX",
    "veiculoLabel": "VEI-0001 · CTD 00M2",
    "prefixo": "VEI-0001",
    "defeito": "Pneu dianteiro com desgaste irregular",
    "dataApontamento": "2026-05-21",
    "horaApontamento": "06:00",
    "prazo": "2026-05-28",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-A",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0002__nc-02",
    "checklistId": "demo-cl-0002",
    "ncItemId": "nc-02",
    "veiculoId": "veiculo_DAQ13S9",
    "placa": "DAQ13S9",
    "modelo": "RANGER",
    "veiculoLabel": "VEI-0002 · DAQ 13S9",
    "prefixo": "VEI-0002",
    "defeito": "Freio traseiro com ruido anormal",
    "dataApontamento": "2026-05-21",
    "horaApontamento": "07:01",
    "prazo": "2026-05-28",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-B",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0003__nc-03",
    "checklistId": "demo-cl-0003",
    "ncItemId": "nc-03",
    "veiculoId": "veiculo_EHB26X6",
    "placa": "EHB26X6",
    "modelo": "S10",
    "veiculoLabel": "VEI-0003 · EHB 26X6",
    "prefixo": "VEI-0003",
    "defeito": "Vazamento de oleo na carter",
    "dataApontamento": "2026-05-20",
    "horaApontamento": "08:02",
    "prazo": "2026-05-27",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-C",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0004__nc-04",
    "checklistId": "demo-cl-0004",
    "ncItemId": "nc-04",
    "veiculoId": "veiculo_FQN39C3",
    "placa": "FQN39C3",
    "modelo": "VW/11.180",
    "veiculoLabel": "VEI-0004 · FQN 39C3",
    "prefixo": "VEI-0004",
    "defeito": "Farol dianteiro com lampada queimada",
    "dataApontamento": "2026-05-20",
    "horaApontamento": "09:03",
    "prazo": "2026-05-27",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-D",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0005__nc-05",
    "checklistId": "demo-cl-0005",
    "ncItemId": "nc-05",
    "veiculoId": "veiculo_GXZ42H0",
    "placa": "GXZ42H0",
    "modelo": "IVECO TECTOR",
    "veiculoLabel": "VEI-0005 · GXZ 42H0",
    "prefixo": "VEI-0005",
    "defeito": "Limpador de para-brisa com folga",
    "dataApontamento": "2026-05-19",
    "horaApontamento": "10:04",
    "prazo": "2026-05-26",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-A",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0006__nc-06",
    "checklistId": "demo-cl-0006",
    "ncItemId": "nc-06",
    "veiculoId": "veiculo_HEL55N7",
    "placa": "HEL55N7",
    "modelo": "HONDA BROS",
    "veiculoLabel": "VEI-0006 · HEL 55N7",
    "prefixo": "VEI-0006",
    "defeito": "Extintor de incendio vencido",
    "dataApontamento": "2026-05-19",
    "horaApontamento": "11:05",
    "prazo": "2026-05-26",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-B",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0007__nc-07",
    "checklistId": "demo-cl-0007",
    "ncItemId": "nc-07",
    "veiculoId": "veiculo_JMX68T4",
    "placa": "JMX68T4",
    "modelo": "MERCEDES MB 1620",
    "veiculoLabel": "VEI-0007 · JMX 68T4",
    "prefixo": "VEI-0007",
    "defeito": "Cinto de seguranca com defeito",
    "dataApontamento": "2026-05-18",
    "horaApontamento": "12:06",
    "prazo": "2026-05-25",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-C",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0008__nc-08",
    "checklistId": "demo-cl-0008",
    "ncItemId": "nc-08",
    "veiculoId": "veiculo_KUJ71Y1",
    "placa": "KUJ71Y1",
    "modelo": "TORO",
    "veiculoLabel": "VEI-0008 · KUJ 71Y1",
    "prefixo": "VEI-0008",
    "defeito": "Espelho retrovisor direito quebrado",
    "dataApontamento": "2026-05-18",
    "horaApontamento": "13:07",
    "prazo": "2026-05-25",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-D",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0009__nc-09",
    "checklistId": "demo-cl-0009",
    "ncItemId": "nc-09",
    "veiculoId": "veiculo_LBV84D8",
    "placa": "LBV84D8",
    "modelo": "HILUX",
    "veiculoLabel": "VEI-0009 · LBV 84D8",
    "prefixo": "VEI-0009",
    "defeito": "Pneu estepe sem condicoes de uso",
    "dataApontamento": "2026-05-17",
    "horaApontamento": "14:08",
    "prazo": "2026-05-24",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-A",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0010__nc-10",
    "checklistId": "demo-cl-0010",
    "ncItemId": "nc-10",
    "veiculoId": "veiculo_MJG97J5",
    "placa": "MJG97J5",
    "modelo": "RANGER",
    "veiculoLabel": "VEI-0010 · MJG 97J5",
    "prefixo": "VEI-0010",
    "defeito": "Bateria com carga insuficiente",
    "dataApontamento": "2026-05-17",
    "horaApontamento": "15:09",
    "prazo": "2026-05-24",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-B",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0011__nc-11",
    "checklistId": "demo-cl-0011",
    "ncItemId": "nc-11",
    "veiculoId": "veiculo_NRT00P2",
    "placa": "NRT00P2",
    "modelo": "S10",
    "veiculoLabel": "VEI-0011 · NRT 00P2",
    "prefixo": "VEI-0011",
    "defeito": "Amortecedor dianteiro com vazamento",
    "dataApontamento": "2026-05-16",
    "horaApontamento": "16:10",
    "prazo": "2026-05-23",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-C",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0012__nc-12",
    "checklistId": "demo-cl-0012",
    "ncItemId": "nc-12",
    "veiculoId": "veiculo_PYE13U9",
    "placa": "PYE13U9",
    "modelo": "VW/11.180",
    "veiculoLabel": "VEI-0012 · PYE 13U9",
    "prefixo": "VEI-0012",
    "defeito": "Faixa reflexiva danificada",
    "dataApontamento": "2026-05-16",
    "horaApontamento": "17:11",
    "prazo": "2026-05-23",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-D",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0013__nc-13",
    "checklistId": "demo-cl-0013",
    "ncItemId": "nc-13",
    "veiculoId": "veiculo_QFR26Z6",
    "placa": "QFR26Z6",
    "modelo": "IVECO TECTOR",
    "veiculoLabel": "VEI-0013 · QFR 26Z6",
    "prefixo": "VEI-0013",
    "defeito": "Tacografo com leitura incorreta",
    "dataApontamento": "2026-05-15",
    "horaApontamento": "06:12",
    "prazo": "2026-05-22",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-A",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0014__nc-14",
    "checklistId": "demo-cl-0014",
    "ncItemId": "nc-14",
    "veiculoId": "veiculo_RNC39E3",
    "placa": "RNC39E3",
    "modelo": "HONDA BROS",
    "veiculoLabel": "VEI-0014 · RNC 39E3",
    "prefixo": "VEI-0014",
    "defeito": "Documentacao do veiculo vencida",
    "dataApontamento": "2026-05-14",
    "horaApontamento": "07:13",
    "prazo": "2026-05-21",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-B",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0015__nc-15",
    "checklistId": "demo-cl-0015",
    "ncItemId": "nc-15",
    "veiculoId": "veiculo_SVP42K0",
    "placa": "SVP42K0",
    "modelo": "MERCEDES MB 1620",
    "veiculoLabel": "VEI-0015 · SVP 42K0",
    "prefixo": "VEI-0015",
    "defeito": "Luz de freio queimada",
    "dataApontamento": "2026-05-13",
    "horaApontamento": "08:14",
    "prazo": "2026-05-20",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-C",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0016__nc-01",
    "checklistId": "demo-cl-0016",
    "ncItemId": "nc-01",
    "veiculoId": "veiculo_TCA55Q7",
    "placa": "TCA55Q7",
    "modelo": "TORO",
    "veiculoLabel": "VEI-0016 · TCA 55Q7",
    "prefixo": "VEI-0016",
    "defeito": "Pneu dianteiro com desgaste irregular",
    "dataApontamento": "2026-05-11",
    "horaApontamento": "09:15",
    "prazo": "2026-05-18",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-D",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0017__nc-02",
    "checklistId": "demo-cl-0017",
    "ncItemId": "nc-02",
    "veiculoId": "veiculo_UKM68V4",
    "placa": "UKM68V4",
    "modelo": "HILUX",
    "veiculoLabel": "VEI-0017 · UKM 68V4",
    "prefixo": "VEI-0017",
    "defeito": "Freio traseiro com ruido anormal",
    "dataApontamento": "2026-05-09",
    "horaApontamento": "10:16",
    "prazo": "2026-05-16",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-A",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0018__nc-03",
    "checklistId": "demo-cl-0018",
    "ncItemId": "nc-03",
    "veiculoId": "veiculo_VSY71A1",
    "placa": "VSY71A1",
    "modelo": "RANGER",
    "veiculoLabel": "VEI-0018 · VSY 71A1",
    "prefixo": "VEI-0018",
    "defeito": "Vazamento de oleo na carter",
    "dataApontamento": "2026-05-07",
    "horaApontamento": "11:17",
    "prazo": "2026-05-14",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-B",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0019__nc-04",
    "checklistId": "demo-cl-0019",
    "ncItemId": "nc-04",
    "veiculoId": "veiculo_WZK84F8",
    "placa": "WZK84F8",
    "modelo": "S10",
    "veiculoLabel": "VEI-0019 · WZK 84F8",
    "prefixo": "VEI-0019",
    "defeito": "Farol dianteiro com lampada queimada",
    "dataApontamento": "2026-05-06",
    "horaApontamento": "12:18",
    "prazo": "2026-05-13",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-C",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0020__nc-05",
    "checklistId": "demo-cl-0020",
    "ncItemId": "nc-05",
    "veiculoId": "veiculo_XGW97L5",
    "placa": "XGW97L5",
    "modelo": "VW/11.180",
    "veiculoLabel": "VEI-0020 · XGW 97L5",
    "prefixo": "VEI-0020",
    "defeito": "Limpador de para-brisa com folga",
    "dataApontamento": "2026-05-03",
    "horaApontamento": "13:19",
    "prazo": "2026-05-10",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-D",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0021__nc-06",
    "checklistId": "demo-cl-0021",
    "ncItemId": "nc-06",
    "veiculoId": "veiculo_YPH00R2",
    "placa": "YPH00R2",
    "modelo": "IVECO TECTOR",
    "veiculoLabel": "VEI-0021 · YPH 00R2",
    "prefixo": "VEI-0021",
    "defeito": "Extintor de incendio vencido",
    "dataApontamento": "2026-05-18",
    "horaApontamento": "14:20",
    "prazo": "2026-05-25",
    "resolvido": true,
    "dataResolvido": "2026-05-20",
    "horaResolvido": "12:20",
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-A",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0022__nc-07",
    "checklistId": "demo-cl-0022",
    "ncItemId": "nc-07",
    "veiculoId": "veiculo_ZWU13W9",
    "placa": "ZWU13W9",
    "modelo": "HONDA BROS",
    "veiculoLabel": "VEI-0022 · ZWU 13W9",
    "prefixo": "VEI-0022",
    "defeito": "Cinto de seguranca com defeito",
    "dataApontamento": "2026-05-16",
    "horaApontamento": "15:21",
    "prazo": "2026-05-23",
    "resolvido": true,
    "dataResolvido": "2026-05-19",
    "horaResolvido": "13:21",
    "reparoValor": 338750,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1021.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-B",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0023__nc-08",
    "checklistId": "demo-cl-0023",
    "ncItemId": "nc-08",
    "veiculoId": "veiculo_ADF26B6",
    "placa": "ADF26B6",
    "modelo": "MERCEDES MB 1620",
    "veiculoLabel": "VEI-0023 · ADF 26B6",
    "prefixo": "VEI-0023",
    "defeito": "Espelho retrovisor direito quebrado",
    "dataApontamento": "2026-05-14",
    "horaApontamento": "16:22",
    "prazo": "2026-05-21",
    "resolvido": true,
    "dataResolvido": "2026-05-18",
    "horaResolvido": "14:22",
    "reparoValor": 352500,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1022.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-C",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0024__nc-09",
    "checklistId": "demo-cl-0024",
    "ncItemId": "nc-09",
    "veiculoId": "veiculo_BLS39G3",
    "placa": "BLS39G3",
    "modelo": "TORO",
    "veiculoLabel": "VEI-0024 · BLS 39G3",
    "prefixo": "VEI-0024",
    "defeito": "Pneu estepe sem condicoes de uso",
    "dataApontamento": "2026-05-13",
    "horaApontamento": "17:23",
    "prazo": "2026-05-20",
    "resolvido": true,
    "dataResolvido": "2026-05-20",
    "horaResolvido": "15:23",
    "reparoValor": 366250,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1023.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-D",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0025__nc-10",
    "checklistId": "demo-cl-0025",
    "ncItemId": "nc-10",
    "veiculoId": "veiculo_CTD42M0",
    "placa": "CTD42M0",
    "modelo": "HILUX",
    "veiculoLabel": "VEI-0025 · CTD 42M0",
    "prefixo": "VEI-0025",
    "defeito": "Bateria com carga insuficiente",
    "dataApontamento": "2026-05-11",
    "horaApontamento": "06:24",
    "prazo": "2026-05-18",
    "resolvido": true,
    "dataResolvido": "2026-05-17",
    "horaResolvido": "08:24",
    "reparoValor": 380000,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1024.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-A",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0026__nc-11",
    "checklistId": "demo-cl-0026",
    "ncItemId": "nc-11",
    "veiculoId": "veiculo_DAQ55S7",
    "placa": "DAQ55S7",
    "modelo": "RANGER",
    "veiculoLabel": "VEI-0026 · DAQ 55S7",
    "prefixo": "VEI-0026",
    "defeito": "Amortecedor dianteiro com vazamento",
    "dataApontamento": "2026-05-09",
    "horaApontamento": "07:25",
    "prazo": "2026-05-16",
    "resolvido": true,
    "dataResolvido": "2026-05-19",
    "horaResolvido": "09:25",
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-B",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0027__nc-12",
    "checklistId": "demo-cl-0027",
    "ncItemId": "nc-12",
    "veiculoId": "veiculo_EHB68X4",
    "placa": "EHB68X4",
    "modelo": "S10",
    "veiculoLabel": "VEI-0027 · EHB 68X4",
    "prefixo": "VEI-0027",
    "defeito": "Faixa reflexiva danificada",
    "dataApontamento": "2026-05-07",
    "horaApontamento": "08:26",
    "prazo": "2026-05-14",
    "resolvido": true,
    "dataResolvido": "2026-05-16",
    "horaResolvido": "10:26",
    "reparoValor": 407500,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1026.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-C",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0028__nc-13",
    "checklistId": "demo-cl-0028",
    "ncItemId": "nc-13",
    "veiculoId": "veiculo_FQN71C1",
    "placa": "FQN71C1",
    "modelo": "VW/11.180",
    "veiculoLabel": "VEI-0028 · FQN 71C1",
    "prefixo": "VEI-0028",
    "defeito": "Tacografo com leitura incorreta",
    "dataApontamento": "2026-05-06",
    "horaApontamento": "09:27",
    "prazo": "2026-05-13",
    "resolvido": true,
    "dataResolvido": "2026-05-18",
    "horaResolvido": "11:27",
    "reparoValor": 421250,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1027.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-D",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0029__nc-14",
    "checklistId": "demo-cl-0029",
    "ncItemId": "nc-14",
    "veiculoId": "veiculo_GXZ84H8",
    "placa": "GXZ84H8",
    "modelo": "IVECO TECTOR",
    "veiculoLabel": "VEI-0029 · GXZ 84H8",
    "prefixo": "VEI-0029",
    "defeito": "Documentacao do veiculo vencida",
    "dataApontamento": "2026-05-01",
    "horaApontamento": "10:28",
    "prazo": "2026-05-08",
    "resolvido": true,
    "dataResolvido": "2026-05-15",
    "horaResolvido": "12:28",
    "reparoValor": 435000,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1028.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-A",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0030__nc-15",
    "checklistId": "demo-cl-0030",
    "ncItemId": "nc-15",
    "veiculoId": "veiculo_HEL97N5",
    "placa": "HEL97N5",
    "modelo": "HONDA BROS",
    "veiculoLabel": "VEI-0030 · HEL 97N5",
    "prefixo": "VEI-0030",
    "defeito": "Luz de freio queimada",
    "dataApontamento": "2026-04-29",
    "horaApontamento": "11:29",
    "prazo": "2026-05-06",
    "resolvido": true,
    "dataResolvido": "2026-05-17",
    "horaResolvido": "13:29",
    "reparoValor": 448750,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1029.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-B",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0031__nc-01",
    "checklistId": "demo-cl-0031",
    "ncItemId": "nc-01",
    "veiculoId": "veiculo_JMX00T2",
    "placa": "JMX00T2",
    "modelo": "MERCEDES MB 1620",
    "veiculoLabel": "VEI-0031 · JMX 00T2",
    "prefixo": "VEI-0031",
    "defeito": "Pneu dianteiro com desgaste irregular",
    "dataApontamento": "2026-04-26",
    "horaApontamento": "12:30",
    "prazo": "2026-05-03",
    "resolvido": true,
    "dataResolvido": "2026-05-14",
    "horaResolvido": "14:30",
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-C",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0032__nc-02",
    "checklistId": "demo-cl-0032",
    "ncItemId": "nc-02",
    "veiculoId": "veiculo_KUJ13Y9",
    "placa": "KUJ13Y9",
    "modelo": "TORO",
    "veiculoLabel": "VEI-0032 · KUJ 13Y9",
    "prefixo": "VEI-0032",
    "defeito": "Freio traseiro com ruido anormal",
    "dataApontamento": "2026-04-23",
    "horaApontamento": "13:31",
    "prazo": "2026-04-30",
    "resolvido": true,
    "dataResolvido": "2026-05-16",
    "horaResolvido": "15:31",
    "reparoValor": 476250,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1031.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-D",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0033__nc-03",
    "checklistId": "demo-cl-0033",
    "ncItemId": "nc-03",
    "veiculoId": "veiculo_LBV26D6",
    "placa": "LBV26D6",
    "modelo": "HILUX",
    "veiculoLabel": "VEI-0033 · LBV 26D6",
    "prefixo": "VEI-0033",
    "defeito": "Vazamento de oleo na carter",
    "dataApontamento": "2026-05-15",
    "horaApontamento": "14:32",
    "prazo": "2026-05-22",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": true,
    "justificativa": "Aguardando peca junto ao fornecedor. Prazo estimado 5 dias uteis.",
    "justificativaData": "2026-05-16",
    "justificativaImagem": null,
    "agendamentoData": "2026-05-20",
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-A",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0034__nc-04",
    "checklistId": "demo-cl-0034",
    "ncItemId": "nc-04",
    "veiculoId": "veiculo_MJG39J3",
    "placa": "MJG39J3",
    "modelo": "RANGER",
    "veiculoLabel": "VEI-0034 · MJG 39J3",
    "prefixo": "VEI-0034",
    "defeito": "Farol dianteiro com lampada queimada",
    "dataApontamento": "2026-05-12",
    "horaApontamento": "15:33",
    "prazo": "2026-05-19",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": true,
    "justificativa": "Aguardando peca junto ao fornecedor. Prazo estimado 5 dias uteis.",
    "justificativaData": "2026-05-13",
    "justificativaImagem": null,
    "agendamentoData": "2026-05-17",
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-B",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0035__nc-05",
    "checklistId": "demo-cl-0035",
    "ncItemId": "nc-05",
    "veiculoId": "veiculo_NRT42P0",
    "placa": "NRT42P0",
    "modelo": "S10",
    "veiculoLabel": "VEI-0035 · NRT 42P0",
    "prefixo": "VEI-0035",
    "defeito": "Limpador de para-brisa com folga",
    "dataApontamento": "2026-05-10",
    "horaApontamento": "16:34",
    "prazo": "2026-05-17",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": true,
    "justificativa": "Aguardando peca junto ao fornecedor. Prazo estimado 5 dias uteis.",
    "justificativaData": "2026-05-11",
    "justificativaImagem": null,
    "agendamentoData": "2026-05-15",
    "processo": "SKY",
    "base": "BASE-E",
    "coordenador": "COORD-C",
    "responsavel": "GABRIEL COSTA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0036__nc-06",
    "checklistId": "demo-cl-0036",
    "ncItemId": "nc-06",
    "veiculoId": "veiculo_PYE55U7",
    "placa": "PYE55U7",
    "modelo": "VW/11.180",
    "veiculoLabel": "VEI-0036 · PYE 55U7",
    "prefixo": "VEI-0036",
    "defeito": "Extintor de incendio vencido",
    "dataApontamento": "2026-05-05",
    "horaApontamento": "17:35",
    "prazo": "2026-05-12",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": true,
    "justificativa": "Aguardando peca junto ao fornecedor. Prazo estimado 5 dias uteis.",
    "justificativaData": "2026-05-06",
    "justificativaImagem": null,
    "agendamentoData": "2026-05-10",
    "processo": "MUNCK",
    "base": "BASE-F",
    "coordenador": "COORD-D",
    "responsavel": "HUGO FERREIRA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0037__nc-07",
    "checklistId": "demo-cl-0037",
    "ncItemId": "nc-07",
    "veiculoId": "veiculo_QFR68Z4",
    "placa": "QFR68Z4",
    "modelo": "IVECO TECTOR",
    "veiculoLabel": "VEI-0037 · QFR 68Z4",
    "prefixo": "VEI-0037",
    "defeito": "Cinto de seguranca com defeito",
    "dataApontamento": "2026-05-20",
    "horaApontamento": "06:36",
    "prazo": "2026-05-27",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-A",
    "base": "BASE-A",
    "coordenador": "COORD-A",
    "responsavel": "CARLOS LIMA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0038__nc-08",
    "checklistId": "demo-cl-0038",
    "ncItemId": "nc-08",
    "veiculoId": "veiculo_RNC71E1",
    "placa": "RNC71E1",
    "modelo": "HONDA BROS",
    "veiculoLabel": "VEI-0038 · RNC 71E1",
    "prefixo": "VEI-0038",
    "defeito": "Espelho retrovisor direito quebrado",
    "dataApontamento": "2026-05-19",
    "horaApontamento": "07:37",
    "prazo": "2026-05-26",
    "resolvido": true,
    "dataResolvido": "2026-05-20",
    "horaResolvido": "13:37",
    "reparoValor": 558750,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1037.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-B",
    "base": "BASE-B",
    "coordenador": "COORD-B",
    "responsavel": "DIEGO SOUZA",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  },
  {
    "id": "demo-cl-0039__nc-09",
    "checklistId": "demo-cl-0039",
    "ncItemId": "nc-09",
    "veiculoId": "veiculo_SVP84K8",
    "placa": "SVP84K8",
    "modelo": "MERCEDES MB 1620",
    "veiculoLabel": "VEI-0039 · SVP 84K8",
    "prefixo": "VEI-0039",
    "defeito": "Pneu estepe sem condicoes de uso",
    "dataApontamento": "2026-05-18",
    "horaApontamento": "08:38",
    "prazo": "2026-05-25",
    "resolvido": false,
    "dataResolvido": null,
    "horaResolvido": null,
    "reparoValor": null,
    "reparoDescricao": null,
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PROC-C",
    "base": "BASE-C",
    "coordenador": "COORD-C",
    "responsavel": "EDUARDO NUNES",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": true
  },
  {
    "id": "demo-cl-0040__nc-10",
    "checklistId": "demo-cl-0040",
    "ncItemId": "nc-10",
    "veiculoId": "veiculo_TCA97Q5",
    "placa": "TCA97Q5",
    "modelo": "TORO",
    "veiculoLabel": "VEI-0040 · TCA 97Q5",
    "prefixo": "VEI-0040",
    "defeito": "Bateria com carga insuficiente",
    "dataApontamento": "2026-05-17",
    "horaApontamento": "09:39",
    "prazo": "2026-05-24",
    "resolvido": true,
    "dataResolvido": "2026-05-19",
    "horaResolvido": "15:39",
    "reparoValor": 586250,
    "reparoDescricao": "Substituicao e reparo realizado pela oficina. OS #1039.",
    "reparoImagens": [],
    "osArquivo": null,
    "justificado": false,
    "justificativa": null,
    "justificativaData": null,
    "justificativaImagem": null,
    "agendamentoData": null,
    "processo": "PICAPE 4X4",
    "base": "BASE-D",
    "coordenador": "COORD-D",
    "responsavel": "FABIO MARTINS",
    "ncFotos": [],
    "problemasAdicionais": "",
    "descricaoProblema": "",
    "imperativo": false
  }
]

export const MOCK_CHECKLISTS_REALIZADOS_TOTAL = 134

export type ChecklistDiaRow = { data: string; realizados: number; comNc: number }

export const MOCK_CHECKLISTS_POR_DIA: ChecklistDiaRow[] = [
  {
    "data": "2026-04-22",
    "realizados": 31,
    "comNc": 10
  },
  {
    "data": "2026-04-23",
    "realizados": 34,
    "comNc": 10
  },
  {
    "data": "2026-04-24",
    "realizados": 17,
    "comNc": 4
  },
  {
    "data": "2026-04-25",
    "realizados": 2,
    "comNc": 0
  },
  {
    "data": "2026-04-26",
    "realizados": 5,
    "comNc": 0
  },
  {
    "data": "2026-04-27",
    "realizados": 26,
    "comNc": 3
  },
  {
    "data": "2026-04-28",
    "realizados": 29,
    "comNc": 9
  },
  {
    "data": "2026-04-29",
    "realizados": 32,
    "comNc": 9
  },
  {
    "data": "2026-04-30",
    "realizados": 15,
    "comNc": 3
  },
  {
    "data": "2026-05-01",
    "realizados": 18,
    "comNc": 3
  },
  {
    "data": "2026-05-02",
    "realizados": 3,
    "comNc": 0
  },
  {
    "data": "2026-05-03",
    "realizados": 6,
    "comNc": 0
  },
  {
    "data": "2026-05-04",
    "realizados": 27,
    "comNc": 8
  },
  {
    "data": "2026-05-05",
    "realizados": 30,
    "comNc": 8
  },
  {
    "data": "2026-05-06",
    "realizados": 33,
    "comNc": 8
  },
  {
    "data": "2026-05-07",
    "realizados": 16,
    "comNc": 3
  },
  {
    "data": "2026-05-08",
    "realizados": 19,
    "comNc": 3
  },
  {
    "data": "2026-05-09",
    "realizados": 4,
    "comNc": 0
  },
  {
    "data": "2026-05-10",
    "realizados": 2,
    "comNc": 0
  },
  {
    "data": "2026-05-11",
    "realizados": 28,
    "comNc": 7
  },
  {
    "data": "2026-05-12",
    "realizados": 31,
    "comNc": 7
  },
  {
    "data": "2026-05-13",
    "realizados": 34,
    "comNc": 6
  },
  {
    "data": "2026-05-14",
    "realizados": 17,
    "comNc": 2
  },
  {
    "data": "2026-05-15",
    "realizados": 20,
    "comNc": 2
  },
  {
    "data": "2026-05-16",
    "realizados": 5,
    "comNc": 1
  },
  {
    "data": "2026-05-17",
    "realizados": 3,
    "comNc": 0
  },
  {
    "data": "2026-05-18",
    "realizados": 29,
    "comNc": 6
  },
  {
    "data": "2026-05-19",
    "realizados": 32,
    "comNc": 6
  },
  {
    "data": "2026-05-20",
    "realizados": 15,
    "comNc": 2
  },
  {
    "data": "2026-05-21",
    "realizados": 18,
    "comNc": 1
  }
]